// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToWeaviate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToWeaviate'](arg1, arg2, arg3);
}

export function GetCollectionItemCount(arg1, arg2) {
  return window['go']['main']['App']['GetCollectionItemCount'](arg1, arg2);
}

export function GetCollectionItems(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetCollectionItems'](arg1, arg2, arg3, arg4, arg5);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HealthCheck(arg1) {
  return window['go']['main']['App']['HealthCheck'](arg1);
}

export function ListCollections(arg1) {
  return window['go']['main']['App']['ListCollections'](arg1);
}

export function ShowDialog() {
  return window['go']['main']['App']['ShowDialog']();
}
