// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {weaviate} from '../models';

export function ConnectToWeaviate(arg1:string,arg2:string,arg3:number):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function HealthCheck(arg1:number):Promise<boolean>;

export function ListCollections(arg1:number):Promise<Array<weaviate.WeviateCollectionInfo>>;

export function ShowDialog():Promise<void>;
