// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {weaviate} from '../models';

export function ConnectToWeaviate(arg1:string,arg2:string,arg3:number):Promise<number>;

export function GetCollectionItemCount(arg1:number,arg2:string):Promise<models.GraphQLResponse>;

export function GetCollectionItems(arg1:number,arg2:string,arg3:Array<string>,arg4:number,arg5:number):Promise<models.GraphQLResponse>;

export function HealthCheck(arg1:number):Promise<boolean>;

export function ListCollections(arg1:number):Promise<Array<weaviate.WeaviateCollectionInfo>>;

export function TestConnection(arg1:string,arg2:string,arg3:number):Promise<boolean>;
